name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20250401

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install texlive-plain-generic

      - name: Build HTML
        run: |
          make local-html
